#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 18, 2019 05:25:05 PM +0300  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join C:/ Leprecoin GUI Leprechaun_with_Beer_PNG_Clipart.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Calisto MT} -size 12 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Lucida Calligraphy} -size 20 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x450+601+389
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -background {saddle brown} -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra43" "buttons_frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {saddle brown} -disabledforeground {#a3a3a3} \
        -font {-family {Old English Text MT} -size 20} -foreground Gold \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Leprecoin 
    vTcl:DefineAlias "$site_3_0.lab44" "leprecoin_label" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background Gold -disabledforeground {#a3a3a3} \
        -font {-family {Calisto MT} -size 12 -slant italic} -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Cancel 
    vTcl:DefineAlias "$site_3_0.but45" "cancel_button" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 0 -y 0 -width 150 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 650 -y 0 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background {dark slate gray} \
        -height 75 -width 125 
    vTcl:DefineAlias "$top.fra46" "mining_frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -background {#2f4f4f} -disabledforeground {#a3a3a3} \
        -font {-family {Lucida Calligraphy} -size 20} -foreground Gold \
        -text {Mining is under progress} 
    vTcl:DefineAlias "$site_3_0.lab47" "mining_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -background {dark slate grey} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join C:/ Leprecoin GUI Leprechaun_with_Beer_PNG_Clipart.png]] 
    vTcl:DefineAlias "$site_3_0.lab48" "lprechaun_label" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 125 -y 120 -width 200 -relwidth 0 -height 164 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 475 -y 120 -width 200 -relwidth 0 -height 164 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 0 -y 0 -width 800 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -y 30 -width 800 -relwidth 0 -height 420 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

