#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 30, 2019 12:20:27 PM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Lucida Calligraphy} -size 14" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Lucida Calligraphy} -size 14 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
vTcl:font:add_font \
    "-family {Lucida Calligraphy} -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x450+1084+535
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Send Gui Window" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -background {dark slate grey} -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra43" "send_frame" vTcl:WidgetProc "Send Gui Window" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {dark slate grey} -disabledforeground {#a3a3a3} \
        -font {-family {Lucida Calligraphy} -size 14} -foreground Gold \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Send to} 
    vTcl:DefineAlias "$site_3_0.lab44" "send_label" vTcl:WidgetProc "Send Gui Window" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {dark slate grey} -disabledforeground {#a3a3a3} \
        -font {-family {Lucida Calligraphy} -size 14} -foreground gold \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Amount 
    vTcl:DefineAlias "$site_3_0.lab46" "amount_label" vTcl:WidgetProc "Send Gui Window" 1
    entry $site_3_0.ent48 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent48" "send_entry" vTcl:WidgetProc "Send Gui Window" 1
    entry $site_3_0.ent49 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent49" "amount_entry" vTcl:WidgetProc "Send Gui Window" 1
    button $site_3_0.but51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background Gold -disabledforeground {#a3a3a3} \
        -font {-family {Calisto MT} -size 12 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Send 
    vTcl:DefineAlias "$site_3_0.but51" "send_button" vTcl:WidgetProc "Send Gui Window" 1
    label $site_3_0.lab43 \
        -background {dark slate gray} -disabledforeground {#a3a3a3} \
        -font {-family {Lucida Calligraphy} -size 9} -foreground red \
        -text {Wrong data was inserted, please enter again} 
    vTcl:DefineAlias "$site_3_0.lab43" "Label1" vTcl:WidgetProc "Send Gui Window" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {dark slate grey} -compound center \
        -disabledforeground {#a3a3a3} \
        -font {-family {Lucida Calligraphy} -size 14} -foreground {old lace} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Balance: } 
    vTcl:DefineAlias "$site_3_0.lab45" "send_label_1" vTcl:WidgetProc "Send Gui Window" 1
    text $site_3_0.tex46 \
        -background {dark slate grey} \
        -font {-family {Lucida Calligraphy} -size 14} -foreground {#fdf5e6} \
        -height 24 -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief flat -selectbackground {#c4c4c4} \
        -selectforeground black -width 64 -wrap word 
    .top42.fra43.tex46 configure -font "-family {Lucida Calligraphy} -size 14"
    .top42.fra43.tex46 insert end text
    vTcl:DefineAlias "$site_3_0.tex46" "Text1" vTcl:WidgetProc "Send Gui Window" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 200 -y 110 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 200 -y 200 -width 100 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 350 -y 110 -width 250 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 350 -y 200 -width 250 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 650 -y 340 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 250 -y 280 -width 314 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 50 -y 30 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex46 \
        -in $site_3_0 -x 50 -y 60 -width 300 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra52 \
        -borderwidth 2 -background {saddle brown} -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra52" "buttons_frame" vTcl:WidgetProc "Send Gui Window" 1
    set site_3_0 $top.fra52
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {saddle brown} -disabledforeground {#a3a3a3} \
        -font {-family {Old English Text MT} -size 20} -foreground Gold \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Leprecoin 
    vTcl:DefineAlias "$site_3_0.lab53" "leprecoin_lable" vTcl:WidgetProc "Send Gui Window" 1
    button $site_3_0.but54 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background Gold -disabledforeground {#a3a3a3} \
        -font {-family {Calisto MT} -size 12 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Back 
    vTcl:DefineAlias "$site_3_0.but54" "back_button" vTcl:WidgetProc "Send Gui Window" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -y 0 -width 150 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 650 -y 0 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 0 -y 30 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 0 -y 0 -width 800 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

