#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 19, 2019 09:43:24 AM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Calisto MT} -size 12 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Old English Text MT} -size 20 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 800x450+617+290
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Transactions Window" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -background {saddle brown} -height 75 -width 125 
    vTcl:DefineAlias "$top.fra43" "buttons_frame" vTcl:WidgetProc "Transactions Window" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -background {saddle brown} -disabledforeground {#a3a3a3} \
        -font {-family {Old English Text MT} -size 20} -foreground Gold \
        -text Leprecoin 
    vTcl:DefineAlias "$site_3_0.lab44" "leprecoin_label" vTcl:WidgetProc "Transactions Window" 1
    button $site_3_0.but45 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background Gold -disabledforeground {#a3a3a3} \
        -font {-family {Calisto MT} -size 12 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Back 
    vTcl:DefineAlias "$site_3_0.but45" "back_button" vTcl:WidgetProc "Transactions Window" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 0 -y 0 -width 150 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 650 -y 0 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -background {dark slate grey} -height 75 -width 125 
    vTcl:DefineAlias "$top.fra46" "transactions_frame" vTcl:WidgetProc "Transactions Window" 1
    set site_3_0 $top.fra46
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr47 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr47" "transactions_text" vTcl:WidgetProc "Transactions Window" 1

    $site_3_0.scr47.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    label $site_3_0.lab49 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} 
    vTcl:DefineAlias "$site_3_0.lab49" "pic_label" vTcl:WidgetProc "Transactions Window" 1
    place $site_3_0.scr47 \
        -in $site_3_0 -x 50 -y 50 -width 400 -relwidth 0 -height 0 \
        -relheight 0.7 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 570 -y 50 -width 198 -relwidth 0 -height 294 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 0 -y 0 -width 800 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -y 30 -width 800 -relwidth 0 -height 420 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

