#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 20, 2019 04:06:53 PM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x450+1071+565
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth -1 -background {saddle brown} -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    button $site_3_0.but53 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background Gold -disabledforeground {#a3a3a3} \
        -font {-family {Calisto MT} -size 12 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Send coins} 
    vTcl:DefineAlias "$site_3_0.but53" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {saddle brown} -disabledforeground {#a3a3a3} \
        -font {-family {Old English Text MT} -size 20} -foreground Gold \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Leprecoin 
    vTcl:DefineAlias "$site_3_0.lab60" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but64 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background Gold -disabledforeground {#a3a3a3} \
        -font {-family {Calisto MT} -size 12 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Try mining} 
    vTcl:DefineAlias "$site_3_0.but64" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but43 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background gold -disabledforeground {#a3a3a3} \
        -font {-family {Calisto MT} -size 12 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Transactions 
    vTcl:DefineAlias "$site_3_0.but43" "Button4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but53 \
        -in $site_3_0 -x 700 -y 0 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -y 0 -width 150 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 600 -y 0 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 500 -y 0 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra48 \
        -borderwidth -1 -background {#2f4f4f} -height 420 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 395 
    vTcl:DefineAlias "$top.fra48" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {dark slate grey} -disabledforeground {#a3a3a3} \
        -font {-family {Lucida Calligraphy} -size 14} -foreground Gold \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Last Tranactions} 
    vTcl:DefineAlias "$site_3_0.lab63" "Label2" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex78 \
        -background {dark slate grey} -borderwidth 2 \
        -font {-family {Lucida Calligraphy} -size 10} -foreground {old lace} \
        -height 10 -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 10 -wrap word 
    .top42.fra48.tex78 configure -font "-family {Lucida Calligraphy} -size 10"
    .top42.fra48.tex78 insert end text
    vTcl:DefineAlias "$site_3_0.tex78" "Text1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -y 0 -width 200 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex78 \
        -in $site_3_0 -x 15 -y 40 -width 450 -relwidth 0 -height 350 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra80 \
        -borderwidth -1 -background {dark slate gray} -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra80" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra80
    label $site_3_0.lab82 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {dark slate grey} -disabledforeground {#a3a3a3} \
        -font {-family {Lucida Calligraphy} -size 14} -foreground Gold \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Current Balance} 
    vTcl:DefineAlias "$site_3_0.lab82" "Label3" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex86 \
        -background {dark slate grey} -borderwidth 0 \
        -font {-family {Lucida Calligraphy} -size 20} -foreground {old lace} \
        -height 4 -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 10 -wrap word 
    .top42.fra80.tex86 configure -font "-family {Lucida Calligraphy} -size 20"
    .top42.fra80.tex86 insert end text
    vTcl:DefineAlias "$site_3_0.tex86" "Text2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab43" "Label5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -y 0 -width 200 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex86 \
        -in $site_3_0 -x 0 -y 40 -width 270 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 90 -y 110 -width 80 -relwidth 0 -height 80 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra83 \
        -borderwidth -1 -background {dark slate grey} -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra83" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra83
    label $site_3_0.lab84 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {dark slate grey} -disabledforeground {#a3a3a3} \
        -font {-family {Lucida Calligraphy} -size 14} -foreground Gold \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Your Address} 
    vTcl:DefineAlias "$site_3_0.lab84" "Label4" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex88 \
        -background {dark slate gray} -borderwidth 0 \
        -font {-family {Lucida Calligraphy} -size 16} -foreground {old lace} \
        -height 50 -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 270 -wrap word 
    .top42.fra83.tex88 configure -font "-family {Lucida Calligraphy} -size 16"
    .top42.fra83.tex88 insert end text
    vTcl:DefineAlias "$site_3_0.tex88" "Text3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab84 \
        -in $site_3_0 -x 0 -y 0 -width 200 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex88 \
        -in $site_3_0 -x 0 -y 40 -width 0 -relwidth 0.9 -height 0 \
        -relheight 0.286 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 0 -y 0 -width 800 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -y 30 -width 500 -relwidth 0 -height 420 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra80 \
        -in $top -x 500 -y 30 -width 300 -relwidth 0 -height 210 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra83 \
        -in $top -x 500 -y 240 -width 300 -relwidth 0 -height 210 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

